### PR TITLE
Compatible with i2cdev driver

### PR DESCRIPTION
**Pull request by imliubo**
Compatible i2cdev 4 macro:
1. I2C_DEV_TAKE_MUTEX
2. I2C_DEV_GIVE_MUTEX
3. I2C_DEV_CHECK
4. I2C_DEV_CHECK_LOGE

[i2cdev.h](https://github.com/UncleRus/esp-idf-lib/blob/master/components/i2cdev/i2cdev.h#L193-L218)

### CODE REVIEW

**Comment by rashedtalukder** [comment]
@ropg, could you review and consider merging? The current i2cdev support is broken anyway since the Espressif i2c driver library needs to be included as done in this PR for the definition of `i2c_port_t`.

**Comment by ropg** [comment]
Whoops, so sorry, had missed this.

**Comment by rashedtalukder** [comment]
There seems to be some issues using I2C Manager with some of the sensor examples provided by Uncle Rus (e.g. [SHT3x temperature/humidity sensor](https://github.com/UncleRus/esp-idf-lib/blob/master/examples/sht3x/main/main.c#L149)). I can't really figure out what the issue is here other than maybe having the function call [I2C_DEV_TAKE_MUTEX](https://github.com/ropg/i2c_manager/blob/master/i2cdev/i2cdev.h#L67-L70) and give always return ESP_OK since it's not needed when doing read/writes. Removing the take/give of the mutex from the driver itself fixes part of the issue but it's still not reading from the peripheral. When I use UncleRus' i2cdev library itself, it is able to read from the register just fine and the example works.

**Comment by ropg** [comment]
I've looked at it a bit, but can't immediately figure out why that wouldn't work. You do know that the driver ignores the any SDA/SCL settings and uses the I2C Manager settings instead, right?

**Comment by rashedtalukder** [comment]
Yes, the issue seems to come partially from the way the UncleRus drivers
take the mutex by calling the take, and then perform the read write. Since
i2c_manager takes the mutex anyway during a read/write it needs to wait for
the first take to timeout. This does happen and an error spits out, but the
issue then is that it doesn't seem to read from the device correctly. I've
tried with this particular sensor package:
https://shop.m5stack.com/products/env-iii-unit-with-temperature-humidity-air-pressure-sensor-sht30-qmp6988?variant=40187936309420,
tried at 100k, 400k, and 1M baud with the internal pullups enabled/disabled
and it just won't read from it. Using i2cdev directly with the sht3x
example, it seems to work just fine.

**Comment by ropg** [comment]
What happens if you change lines 53 and 57 in i2cdev.c also to `return ESP_OK;` ?

Our operations already do locking themselves, so we don't really have to care about manual locking from this code...

**Comment by rashedtalukder** [comment]
Agreed and I tried that. Still didn't successfully read from the device. I also modified the device driver to remove the call to take/give in all lines [e.g. 238 & 241](https://github.com/UncleRus/esp-idf-lib/blob/master/components/sht3x/sht3x.c#L238) and that didn't work either. The peripheral address being passed in is correct (0x44) and the register addresses should be the exact same as i2cdev as well.

**Pull request merged**
